### PR TITLE
Fix CHEF-3694 warnings

### PR DESCRIPTION
**Pull request by dhoer**
Get rid of the following messages:
```
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Cloning resource attributes for script[Install Android SDK platforms and tools] from prior resource (CHEF-3694)
       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'

       [2015-07-09T03:59:22+00:00] WARN: Previous script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
       [2015-07-09T03:59:22+00:00] WARN: Current  script[Install Android SDK platforms and tools]: /tmp/kitchen/cookbooks/android-sdk/recipes/default.rb:113:in `block in from_file'
```

### CODE REVIEW

**Comment by dhoer** [comment]
Please let me know if you don't plan to release this any time soon. I plan to release this to supermarket as android_sdk if this project is no longer maintained.

**Comment by dhoer** [comment]
I have updated test-kitchen and ran all of the test successfully.

**Comment by gildegoma** [comment]
@dhoer thanks a lot, this looks great! Please let me some time to review it. 

You're right that I have been neglecting to release on community/supermarket, and I am sorry for that. I'll comment on this too and I would love to share the maintenance of this cookbook with interested people like you :)

**Comment by dhoer** [comment]
@gildegoma Thanks for the quick response.  I appreciate it.

**Comment by gildegoma** [comment]
@dhoer @rjaros87 I've integrated all these changes (with some additional changes). Please next time, I'd really appreciate to receive pull requests based on feature branches. Having to deal with your "master moving target" daunted me to start the review process and slowed the process in my opinion.

Anyway thank you both for your patience and contributions :)

**Comment by gildegoma** [comment]
PS: I'll aim at publishing 0.2.0 to supermarket in the following days.

**Pull request closed without merging**
